### ISSUE TITLE
Testing and CI

### ISSUE THREAD

**Issue by rye** [kotct/dot#53]
I think we should really look into improving some of the ways we interact with users.  We should try to deal with edge cases in a smarter way, and generally clean up our code.  How do we feel about using CI and tests?  Testing our existing code might evoke good change in our codebase.

#### Task List:

- [x] #61 Add testing framework and integration with Travis CI, using buttercup
- [x] #75 Add coverage support and reporting to Coveralls using undercover
- [ ] Write tests for existing code
- [ ] Add linting support, fix linting issues, and check linting in Travis CI

**Comment by cg505** [comment]
I'm doing research rn on the best approach for testing. We also should get linting set up and put both of those into CI. Suggestions on CI are welcome. I'll update this at some point soon with a roadmap for testing/linting.

**Comment by cg505** [comment]
I'm thinking we should use [buttercup](https://github.com/jorgenschaefer/emacs-buttercup) for tests.

**Comment by cg505** [comment]
Linting will be a combo of [CEDET's checkdoc](http://cedet.sourceforge.net/checkdoc.shtml) and [elisp-lint](https://github.com/AdrieanKhisbe/elisp-lint).

**Comment by cg505** [comment]
I'm gonna start work on this using these. lmk asap if you have an issue with that. planning on using travis

**Comment by cg505** [comment]
I edited the initial comment to include a task list.

**Comment by rye** [comment]
I'm not sure about using Coveralls out of necessity.  Do you know if [CodeClimate](https://codeclimate.com) supports EmacsLisp?

**Comment by cg505** [comment]
I'm pretty sure it doesn't. I already have basic Coveralls support in the coverage-reporting branch. The overhead is pretty minimal. I'm not super satisfied with it at this point, which is why I haven't opened a PR, but at the same time, it's kinda a "why not" thing.

**Comment by cg505** [comment]
Are we good with using undercover? Due to the way coverage libraries for emacs lisp are implemented, it will only show coverage for files that are at least a little tested... so the percentages may be off at first. Still should be a useful tool and I already pretty much have it implemented.

**Comment by rye** [comment]
I'm open to whatever you have, so long as it works.
